# Generated by Django 3.1 on 2020-09-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsroasts',
            name='post_type',
            field=models.CharField(choices=[('boast', 'Boast'), ('roast', 'Roast')], default='Boast', max_length=32, unique=True),
        ),
    ]
