# Generated by Django 3.1 on 2020-09-29 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_boastsroasts_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsroasts',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boastsroasts',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
